import PaymentBaseComponent from './src/components/PaymentBaseComponent';
import IdealComponent from './src/components/IdealComponent';

export default {
  multisafepay: PaymentBaseComponent,
  multisafepay_ideal: IdealComponent,
  multisafepay_afterpay: PaymentBaseComponent,
  multisafepay_alipay: PaymentBaseComponent,
  multisafepay_amex: PaymentBaseComponent,
  multisafepay_applepay: PaymentBaseComponent,
  multisafepay_bancontact: PaymentBaseComponent,
  multisafepay_banktransfer: PaymentBaseComponent,
  multisafepay_belfius: PaymentBaseComponent,
  multisafepay_cbc: PaymentBaseComponent,
  multisafepay_creditcard: PaymentBaseComponent,
  multisafepay_directbanktransfer: PaymentBaseComponent,
  multisafepay_directdebit: PaymentBaseComponent,
  multisafepay_dotpay: PaymentBaseComponent,
  multisafepay_einvoicing: PaymentBaseComponent,
  multisafepay_eps: PaymentBaseComponent,
  multisafepay_giropay: PaymentBaseComponent,
  multisafepay_idealqr: PaymentBaseComponent,
  multisafepay_in3: PaymentBaseComponent,
  multisafepay_inghomepay: PaymentBaseComponent,
  multisafepay_kbc: PaymentBaseComponent,
  multisafepay_klarna: PaymentBaseComponent,
  multisafepay_maestro: PaymentBaseComponent,
  multisafepay_mastercard: PaymentBaseComponent,
  multisafepay_payafter: PaymentBaseComponent,
  multisafepay_paypal: PaymentBaseComponent,
  multisafepay_paysafecard: PaymentBaseComponent,
  multisafepay_santander: PaymentBaseComponent,
  multisafepay_sofort: PaymentBaseComponent,
  multisafepay_trustly: PaymentBaseComponent,
  multisafepay_trustpay: PaymentBaseComponent,
  multisafepay_visa: PaymentBaseComponent,
  multisafepay_babygiftcard: PaymentBaseComponent,
  multisafepay_boekenbon: PaymentBaseComponent,
  multisafepay_fashioncheque: PaymentBaseComponent,
  multisafepay_fashiongiftcard: PaymentBaseComponent,
  multisafepay_fietsenbon: PaymentBaseComponent,
  multisafepay_gezondheidsbon: PaymentBaseComponent,
  multisafepay_givacard: PaymentBaseComponent,
  multisafepay_good4fun: PaymentBaseComponent,
  multisafepay_goodcard: PaymentBaseComponent,
  multisafepay_nationaletuinbon: PaymentBaseComponent,
  multisafepay_parfumcadeaukaart: PaymentBaseComponent,
  multisafepay_podiumcadeaukaart: PaymentBaseComponent,
  multisafepay_sportenfit: PaymentBaseComponent,
  multisafepay_vvvcadeaukaart: PaymentBaseComponent,
  multisafepay_webshopgiftcard: PaymentBaseComponent,
  multisafepay_wellnessgiftcard: PaymentBaseComponent,
  multisafepay_wijncadeau: PaymentBaseComponent,
  multisafepay_winkelcheque: PaymentBaseComponent,
  multisafepay_yourgift: PaymentBaseComponent,
};
